spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: Id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
              # packages: "*"
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=messages_db;trustServerCertificate=true;
    username: sa
    password: pa55w0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9292
